spring.application.name=bingoloot

# 1. Conexão com o banco (Correto)
spring.datasource.url=jdbc:sqlite:bingoloot.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# 2. Dialeto do Hibernate (Correto para Spring Boot 3+)
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# 3. Comportamento do banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true